### ISSUE TITLE
how to find 16S sequences

### ISSUE THREAD

**Issue by jotech** [jstansfield0/HMP2Data#1]
I'm sorry for missing the obvious, but where can I find the actual 16S sequence for each otu?

```R
library(HMP2Data)
ibd <- IBD16S()
ibd@otu_table[1:5,1:5]
ibd@tax_table[1:5,]
```

**Comment by zhaoni153** [comment]
Hello,

***@***.***_table

gives the OTU table, with each row representing an OTU and each column representing a sample.


For example, IP8BSoli represents Belnapia in the tax table.

best,

Ni




-- Ni Zhao, PhD
Associate Professor of Biostatistics
Johns Hopkins University
________________________________
From: jo ***@***.***>
Sent: Thursday, April 11, 2024 11:59 AM
To: jstansfield0/HMP2Data ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jstansfield0/HMP2Data] how to find 16S sequences (Issue #1)


      External Email - Use Caution



I'm sorry for missing the obvious, but where can I find the actual 16S sequence for each otu?

library(HMP2Data)
ibd <- IBD16S()
***@***.***_table[1:5,1:5]
***@***.***_table[1:5,]

**Comment by jotech** [comment]
Hi Ni

Many thanks for your answer!

This answers how to link OTU and taxonomic tables, but how can I access the actual 16S sequence (dna) for each OTU?

**Comment by zhaoni153** [comment]
Each OTU is a cluster of sequencings, and thus there is no way to match one sequence to an OTU.

There might be a way to tell which set of sequences are mapped to which OTU. However, I am not very familiar with the upstream analysis.

Thanks ,
Ni

-- Ni Zhao, PhD
Associate Professor of Biostatistics
Johns Hopkins University
________________________________

**Comment by jotech** [comment]
Thanks, you are right. I was mixing OTU and ASV. 

Still, tracking the sequences involved in each cluster would be helpful, but I see that this might be beyond the scope of the package.
